### ISSUE TITLE
Palantir plotting

### ISSUE THREAD

**Issue by mqlin0** [siegert-lab/MorphOMICs_legacy#7]
Hi! I'm trying to implement the Palantir analysis from your paper, but I'm confused on how to continue after generating the force directed layout. I've tried replicating the Palantir and Harmony demo notebooks from their Githubs, but I haven't had any success.

It would be great if you could share how you generated your plots (specifically for the Ckp25 datasets). Thanks so much!

**Comment by AminAlam** [comment]
Please use the codes in [this repo](https://github.com/siegert-lab/morphOMICs_v2). There are also some super helpful tutorials made by Ryan which you can use.
